name = "navsphere"
compatibility_date = "2026-05-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liSYJtfVErlDfZuk"
GITHUB_OWNER = "lishanganshijie-hue"
GITHUB_REPO = "navsphere-data"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-data-5oc.pages.dev"
NEXT_PUBLIC_API_URL="https://navsphere-data-5oc.pages.dev"

